### ISSUE TITLE
Highlighting of additional log files

### ISSUE THREAD

**Issue by asins** [coteditor/CotEditor#1466]
**Is your feature request related to a problem? Please describe.**
The editor lacks syntax highlighting for `.log` files.  

**Describe the solution you'd like**
I would like to incorporate highlighting for certain content such as dates, times, property names and values in JSON formatted data, syntax errors, and character highlighting for log levels such as INFO/WARNING/ERROR/DEBUG. 

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/898354/229267901-d13a3e79-78b8-4d24-b5e9-ad6fe0694784.png)

**Document Content**
`Log.yml` Document Content:

```yml
attributes:
- beginString: (?<= )\d{2}:\d{2}:\d{2}\.\d{3}(?= )
  regularExpression: true
characters: []
commands:
- beginString: System.err:[^\n]+\n
  regularExpression: true
commentDelimiters: {}
comments: []
completions: []
extensions: []
filenames: []
interpreters: []
keywords:
- beginString: ^(?:\d{2}|\d{4}-)?\d{2}-\d{2}
  description: date
  endString: ' '
  ignoreCase: false
  regularExpression: true
metadata:
  author: Asins
  lastModified: '2023-04-01'
  version: '1.0'
numbers: []
outlineMenu: []
strings: []
types:
- beginString: (?<= )(?:D|DEBUG|Debug)(?= )
  regularExpression: true
- beginString: (?<= )(?:E|ERROR|Error|Err)(?= )
  description: 日志级别
  regularExpression: true
- beginString: (?<= )(?:I|INFO|Info)(?= )
  regularExpression: true
- beginString: (?<= )(?:W|WARN|Warn|WARNING|Warning)(?= )
  regularExpression: true
- beginString: \[(?:WARN|INFO|ERROR)(?::[^\]]+)?\]
  ignoreCase: false
  regularExpression: true
values: []
variables:
- beginString: '"[\w\d-]+"(?=:\s*")'
  description: JSON属性名
  ignoreCase: true
  regularExpression: true
- beginString: (?<=":)".*?(?<!\\)"(?=[},])
  description: JSON属性值为字符串
  regularExpression: true
- beginString: (?<=":)\d+(?=[},])
  description: JSON属性值为数字
  regularExpression: true
```
