### ISSUE TITLE
Elixir syntax highlight does not import

### ISSUE THREAD

**Issue by hl** [coteditor/CotEditor#1806]
### Description

Hi, first of all, amazing editor. I'm planning on using this for the Elixir language and I translated the Ruby syntax highlighting to Elixir but when I try to import, it does not do anything.

### To Reproduce

1. Grab the Ruby.yml
2. Ask Claude.ai to translate it to Elixir
3. Open Cot, go to settings -> Format
4. Try to import Elixir.yml

### Expected behavior

The Elixir syntax to show up in the list of available syntaxes

### CotEditor version

5.0.8

### macOS version

15.3

### Additional context

```yaml
attributes: []
characters: []
commands:
- beginString: __info__
- beginString: apply
- beginString: binary_part
- beginString: bit_size
- beginString: byte_size
- beginString: elem
- beginString: exit
- beginString: function_exported?
- beginString: get_in
- beginString: hd
- beginString: inspect
- beginString: is_atom
- beginString: is_binary
- beginString: is_bitstring
- beginString: is_boolean
- beginString: is_float
- beginString: is_function
- beginString: is_integer
- beginString: is_list
- beginString: is_map
- beginString: is_number
- beginString: is_pid
- beginString: is_port
- beginString: is_reference
- beginString: is_tuple
- beginString: length
- beginString: map_size
- beginString: node
- beginString: put_elem
- beginString: put_in
- beginString: rem
- beginString: round
- beginString: self
- beginString: send
- beginString: spawn
- beginString: spawn_link
- beginString: spawn_monitor
- beginString: struct
- beginString: throw
- beginString: tl
- beginString: trunc
- beginString: tuple_size
commentDelimiters:
  beginDelimiter: '#'
  endDelimiter: ''
  inlineDelimiter: '#'
comments: []
completions: []
extensions:
- keyString: ex
- keyString: exs
filenames:
- keyString: mix.exs
interpreters:
- keyString: elixir
keywords:
- beginString: \bdefmodule\s
  regularExpression: true
- beginString: alias
- beginString: and
- beginString: begin
- beginString: case
- beginString: cond
- beginString: def
- beginString: defp
- beginString: do
- beginString: else
- beginString: end
- beginString: fn
- beginString: for
- beginString: if
- beginString: import
- beginString: in
- beginString: not
- beginString: or
- beginString: quote
- beginString: receive
- beginString: require
- beginString: rescue
- beginString: try
- beginString: unless
- beginString: when
- beginString: with
kind: code
metadata:
  author: Henricus Louwhoff
  description: Maintained by Henricus Louwhoff.
  distributionURL: https://github.com/hl/elixir-language-support
  lastModified: '2025-02-17'
  license: MIT
  version: 1.0.0
numbers:
- beginString: \b0b[01_]+\b
  description: binary
  ignoreCase: true
  regularExpression: true
- beginString: \b0o[0-7_]+\b
  description: octal
  ignoreCase: true
  regularExpression: true
- beginString: \b0x[0-9a-f_]+\b
  description: hexadecimal
  ignoreCase: true
  regularExpression: true
- beginString: \b[0-9][0-9_]*\.[0-9_]+([eE][-+]?[0-9_]+)?\b
  description: float
  regularExpression: true
- beginString: \b[0-9][0-9_]*\b
  description: integer
  regularExpression: true
outlineMenu:
- beginString: (^[\t ]*defmodule)[\t ]+(\w*)
  description: module
  keyString: $1 $2
  underline: true
- beginString: (^[\t ]*defp?)[\t ]+([^\s(]*)
  description: function
  italic: true
  keyString: $1 $2
strings:
- beginString: '"'
  endString: '"'
- beginString: '"""'
  endString: '"""'
- beginString: '\'''
  endString: '\'''
- beginString: ''''
  endString: ''''
- beginString: ~[sS]?\{.*?\}
  regularExpression: true
- beginString: ~[sS]?\[.*?\]
  regularExpression: true
- beginString: ~[sS]?\(.*?\)
  regularExpression: true
- beginString: ~[sS]?<.*?>
  regularExpression: true
- beginString: ~[sS]?\|.*?\|
  regularExpression: true
- beginString: ~[sS]?\'.*?\'
  regularExpression: true
- beginString: ~[sS]?".*?"
  regularExpression: true
types:
- beginString: Atom
- beginString: Binary
- beginString: BitString
- beginString: Float
- beginString: Function
- beginString: Integer
- beginString: List
- beginString: Map
- beginString: PID
- beginString: Port
- beginString: Reference
- beginString: Tuple
values:
- beginString: :\w+
  regularExpression: true
- beginString: true
- beginString: false
- beginString: nil
variables:
- beginString: @\w+
  regularExpression: true
- beginString: \b_\w*
  regularExpression: true
- beginString: \b[a-z_]\w*
  regularExpression: true 
```
