### ISSUE TITLE
Does not work as expected IC check box of syntax highlighting

### ISSUE THREAD

**Issue by yuhei-mukoyama** [coteditor/CotEditor#519]
## 環境 

- CotEditor: 2.4.3 (108)
- システム: OS X バージョン 10.11.3（ビルド 15D21）
- 言語環境: 日本語

## 簡単な説明

シンタックスハイライトの設定項目「IC」チェックを入れているのに、ハイライトされない。

## 不具合が発生したときに行っていた操作、または再現手順

<img width="615" alt="2016-03-07 15 19 40" src="https://cloud.githubusercontent.com/assets/5656927/13562170/a404bb3e-e478-11e5-933e-e7940f718e96.png">

上のウィンドウは「IC」チェックを利用せず、大文字から始まるもの、小文字から始まるもの両方を個別に定義したもの [Sytanx Test (No IC)] を使用。

下のウィンドウは「IC」チェックを利用して、大文字から始まるものだけを定義したもの [Sytanx Test (IC)] を使用。

また、シンタックスハイライトを編集直後などは、再カラーリングを行っても「IC」のチェックを入れたキーワードは一切ハイライトされない。ファイルを開き直すか、ウィンドウを新規に作り直すことで、設定したキーワードと完全一致する場合にのみ、ハイライトされる（= 小文字大文字が一致しないものはハイライトされない）。

## Syntax File

Syntax Test (IC)
```yaml
extensions: []
filenames: []
comments: []
outlineMenu: []
completions: []
metadata: {}
numbers: []
commands: []
values: []
keywords:
- beginString: "Keyword"
  ignoreCase: true
attributes: []
strings: []
types: []
commentDelimiters: {}
interpreters: []
characters: []
variables: []
```

Syntax Test (No IC)
```yaml
extensions: []
filenames: []
comments: []
outlineMenu: []
completions: []
metadata: {}
numbers: []
commands: []
values: []
keywords:
- beginString: "Keyword"
- beginString: "keyword"
attributes: []
strings: []
types: []
commentDelimiters: {}
interpreters: []
variables: []
characters: []
```
